using AndroidBase.Attributes;

namespace AlhambraScoringAndroid.GamePlay
{
    public enum ExpansionModule
    {
        [DescriptionResourceAttribute(Resource.String.viziers_favour)]
        [ImageAttribute(Resource.Drawable.ViziersFavour)]
        ExpansionViziersFavour,
        [DescriptionResourceAttribute(Resource.String.currency_exchange_cards)]
        [ImageAttribute(Resource.Drawable.CurrencyExchangeCard)]
        ExpansionCurrencyExchangeCards,
        [DescriptionResourceAttribute(Resource.String.bonus_cards)]
        [ImageAttribute(Resource.Drawable.BonusCard)]
        ExpansionBonusCards,
        [DescriptionResourceAttribute(Resource.String.squares)]
        [ImageAttribute(Resource.Drawable.Square)]
        ExpansionSquares,
        [DescriptionResourceAttribute(Resource.String.city_gates)]
        [ImageAttribute(Resource.Drawable.CityGates)]
        ExpansionCityGates,
        [DescriptionResourceAttribute(Resource.String.diamonds)]
        [ImageAttribute(Resource.Drawable.Diamonds)]
        ExpansionDiamonds,
        [DescriptionResourceAttribute(Resource.String.characters)]
        [ImageAttribute(Resource.Drawable.CharacterTheWiseMan)]
        ExpansionCharacters,
        [DescriptionResourceAttribute(Resource.String.camps)]
        [ImageAttribute(Resource.Drawable.Camp)]
        ExpansionCamps,
        [DescriptionResourceAttribute(Resource.String.city_walls)]
        [ImageAttribute(Resource.Drawable.CityWalls)]
        ExpansionCityWalls,
        [DescriptionResourceAttribute(Resource.String.thieves)]
        [ImageAttribute(Resource.Drawable.Thieve)]
        ExpansionThieves,
        [DescriptionResourceAttribute(Resource.String.change)]
        [ImageAttribute(Resource.Drawable.Change)]
        ExpansionChange,
        [DescriptionResourceAttribute(Resource.String.street_trader)]
        [ImageAttribute(Resource.Drawable.StreetTrader)]
        ExpansionStreetTrader,
        [DescriptionResourceAttribute(Resource.String.treasure_chamber)]
        [ImageAttribute(Resource.Drawable.TreasureChamber)]
        ExpansionTreasureChamber,
        [DescriptionResourceAttribute(Resource.String.master_builders)]
        [ImageAttribute(Resource.Drawable.MasterBuilder)]
        ExpansionMasterBuilders,
        [DescriptionResourceAttribute(Resource.String.invaders)]
        [ImageAttribute(Resource.Drawable.Invaders)]
        ExpansionInvaders,
        [DescriptionResourceAttribute(Resource.String.bazaars)]
        [ImageAttribute(Resource.Drawable.Bazaar)]
        ExpansionBazaars,
        [DescriptionResourceAttribute(Resource.String.new_score_cards)]
        [ImageAttribute(Resource.Drawable.NewScoreCards)]
        ExpansionNewScoreCards,
        [DescriptionResourceAttribute(Resource.String.power_of_sultan)]
        [ImageAttribute(Resource.Drawable.PowerOfSultan)]
        ExpansionPowerOfSultan,
        [DescriptionResourceAttribute(Resource.String.caravanserai)]
        [ImageAttribute(Resource.Drawable.Caravanserai)]
        ExpansionCaravanserai,
        [DescriptionResourceAttribute(Resource.String.art_of_the_moors)]
        [ImageAttribute(Resource.Drawable.ArtOfTheMoors)]
        ExpansionArtOfTheMoors,
        [DescriptionResourceAttribute(Resource.String.falconers)]
        [ImageAttribute(Resource.Drawable.Falconers)]
        ExpansionFalconers,
        [DescriptionResourceAttribute(Resource.String.watchtowers)]
        [ImageAttribute(Resource.Drawable.Watchtower)]
        ExpansionWatchtowers,
        [DescriptionResourceAttribute(Resource.String.building_sites)]
        [ImageAttribute(Resource.Drawable.BuildingSites)]
        ExpansionBuildingSites,
        [DescriptionResourceAttribute(Resource.String.exchange_certificates)]
        [ImageAttribute(Resource.Drawable.ExchangeCertificates)]
        ExpansionExchangeCertificates,
        [DescriptionResourceAttribute(Resource.String.magical_buildings)]
        [ImageAttribute(Resource.Drawable.MagicalBuildings)]
        QueenieMagicalBuildings,
        [DescriptionResourceAttribute(Resource.String.medina)]
        [ImageAttribute(Resource.Drawable.Medina)]
        QueenieMedina,
        [DescriptionResourceAttribute(Resource.String.new_building_grounds)]
        [ImageAttribute(Resource.Drawable.NewBuildingGrounds)]
        DesignerNewBuildingGrounds,
        [DescriptionResourceAttribute(Resource.String.major_construction_projects)]
        [ImageAttribute(Resource.Drawable.MajorConstructionProjects)]
        DesignerMajorConstructionProjects,
        [DescriptionResourceAttribute(Resource.String.palace_staff)]
        [ImageAttribute(Resource.Drawable.Servant)]
        DesignerPalaceStaff,
        [DescriptionResourceAttribute(Resource.String.orchards)]
        [ImageAttribute(Resource.Drawable.Fruit)]
        DesignerOrchards,
        [DescriptionResourceAttribute(Resource.String.travelling_craftsmen)]
        [ImageAttribute(Resource.Drawable.TravellingCraftsman)]
        DesignerTravellingCraftsmen,
        [DescriptionResourceAttribute(Resource.String.bathhouses)]
        [ImageAttribute(Resource.Drawable.Bathhouse)]
        DesignerBathhouses,
        [DescriptionResourceAttribute(Resource.String.wishing_well)]
        [ImageAttribute(Resource.Drawable.WishingWell)]
        DesignerWishingWell,
        [DescriptionResourceAttribute(Resource.String.fresh_colors)]
        [ImageAttribute(Resource.Drawable.FreshColors)]
        DesignerFreshColors,
        [DescriptionResourceAttribute(Resource.String.palace_designers)]
        [ImageAttribute(Resource.Drawable.PalaceDesigner)]
        DesignerPalaceDesigners,
        [DescriptionResourceAttribute(Resource.String.alhambra_zoo)]
        [ImageAttribute(Resource.Drawable.Animal)]
        DesignerAlhambraZoo,
        [DescriptionResourceAttribute(Resource.String.gates_without_end)]
        [ImageAttribute(Resource.Drawable.GatesWithoutEnd)]
        DesignerGatesWithoutEnd,
        [DescriptionResourceAttribute(Resource.String.buildings_of_power)]
        [ImageAttribute(Resource.Drawable.BuildingOfPower)]
        DesignerBuildingsOfPower,
        [DescriptionResourceAttribute(Resource.String.extensions)]
        [ImageAttribute(Resource.Drawable.Extension)]
        DesignerExtensions,
        [DescriptionResourceAttribute(Resource.String.handymen)]
        [ImageAttribute(Resource.Drawable.Handyman)]
        DesignerHandymen,
        [DescriptionResourceAttribute(Resource.String.personal_building_market)]
        [ImageAttribute(Resource.Drawable.PersonalBuildingMarket)]
        FanPersonalBuildingMarket,
        [DescriptionResourceAttribute(Resource.String.treasures)]
        [ImageAttribute(Resource.Drawable.Treasure)]
        FanTreasures,
        [DescriptionResourceAttribute(Resource.String.caliphs_guidelines)]
        [ImageAttribute(Resource.Drawable.Mission1)]
        FanCaliphsGuidelines,
        [DescriptionResourceAttribute(Resource.String.new_market)]
        [ImageAttribute(Resource.Drawable.NewMarket)]
        NewMarket,

        Granada,
    }
}