using AndroidBase.Attributes;

namespace AlhambraScoringAndroid.GamePlay
{
    public enum SetupInstructions
    {
        [DescriptionResourceAttribute(Resource.String.instruction_put_buildings_of_power_tiles)]
        PutBuildingsOfPowerTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_put_camp_tiles)]
        PutCampTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_put_bazaars_tiles)]
        PutBazaarsTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_put_magical_buildings_tiles)]
        PutMagicalBuildingsTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_put_medina_tiles)]
        PutMedinaTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_put_new_building_grounds_tiles)]
        PutNewBuildingGroundsTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_put_bathhouse_tiles)]
        PutBathhouseTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_put_wishing_well_tiles)]
        PutWishingWellTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_building_tiles)]
        ShuffleBuildingTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_trader)]
        DealTrader,
        [DescriptionResourceAttribute(Resource.String.instruction_place_buildings)]
        PlaceBuildings,
        [DescriptionResourceAttribute(Resource.String.instruction_give_buildings_to_dirk)]
        GiveBuildingsToDirk,
        [DescriptionResourceAttribute(Resource.String.instruction_granada_shuffle_building_tiles)]
        GranadaShuffleBuildingTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_granada_place_buildings)]
        GranadaPlaceBuildings,

        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_squares)]
        ShuffleSquares,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_watchtowers)]
        ShuffleWatchtowers,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_major_construction_projects)]
        ShuffleMajorConstructionProjects,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_gate_board)]
        ShuffleGateBoard,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_extensions)]
        ShuffleExtensions,

        [DescriptionResourceAttribute(Resource.String.instruction_remove_card_deck)]
        RemoveCardDeck,
        [DescriptionResourceAttribute(Resource.String.instruction_put_diamond_cards)]
        PutDiamondCards,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_cards)]
        ShuffleCards,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_money)]
        DealMoney,
        [DescriptionResourceAttribute(Resource.String.instruction_place_cards)]
        PlaceCards,
        [DescriptionResourceAttribute(Resource.String.instruction_divide_cards)]
        DivideCards,
        [DescriptionResourceAttribute(Resource.String.instruction_put_2_scoring_cards)]
        Put2ScoringCards,
        [DescriptionResourceAttribute(Resource.String.instruction_put_1_scoring_card_middle)]
        Put1ScoringCardMiddle,
        [DescriptionResourceAttribute(Resource.String.instruction_put_currency_exchange_cards)]
        PutCurrencyExchangeCards,
        [DescriptionResourceAttribute(Resource.String.instruction_put_city_gates_cards)]
        PutCityGatesCards,
        [DescriptionResourceAttribute(Resource.String.instruction_put_characters)]
        PutCharacters,
        [DescriptionResourceAttribute(Resource.String.instruction_put_city_walls)]
        PutCityWalls,
        [DescriptionResourceAttribute(Resource.String.instruction_put_master_builders)]
        PutMasterBuilders,
        [DescriptionResourceAttribute(Resource.String.instruction_put_master_builders_6)]
        PutMasterBuilders6,
        [DescriptionResourceAttribute(Resource.String.instruction_put_power_of_sultan)]
        PutPowerOfSultan,
        [DescriptionResourceAttribute(Resource.String.instruction_join_piles)]
        JoinPiles,

        [DescriptionResourceAttribute(Resource.String.instruction_deal_bonus_cards_3)]
        DealBonusCards3,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_bonus_cards_2)]
        DealBonusCards2,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_bonus_cards_1)]
        DealBonusCards1,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_thieves_4)]
        DealThieves4,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_thieves_3)]
        DealThieves3,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_thieves_2)]
        DealThieves2,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_master_builders)]
        DealMasterBuilders,

        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_invasion)]
        ShuffleInvasion,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_scout)]
        ShuffleScout,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_caravanserai)]
        ShuffleCaravanserai,

        [DescriptionResourceAttribute(Resource.String.instruction_deal_vizier)]
        DealVizier,
        [DescriptionResourceAttribute(Resource.String.instruction_place_city_gates)]
        PlaceCityGates,
        [DescriptionResourceAttribute(Resource.String.instruction_place_city_walls)]
        PlaceCityWalls,
        [DescriptionResourceAttribute(Resource.String.instruction_place_change)]
        PlaceChange,
        [DescriptionResourceAttribute(Resource.String.instruction_place_trader)]
        PlaceTrader,
        [DescriptionResourceAttribute(Resource.String.instruction_place_trader_tiles)]
        PlaceTraderTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_place_treasure_chamber)]
        PlaceTreasureChamber,
        [DescriptionResourceAttribute(Resource.String.instruction_place_power_of_sultan)]
        PlacePowerOfSultan,
        [DescriptionResourceAttribute(Resource.String.instruction_place_caravanserai)]
        PlaceCaravanserai,
        [DescriptionResourceAttribute(Resource.String.instruction_place_art_of_the_moors)]
        PlaceArtOfTheMoors,
        [DescriptionResourceAttribute(Resource.String.instruction_place_falcons)]
        PlaceFalcons,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_building_sites)]
        ShuffleBuildingSites,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_exchange_certificate)]
        DealExchangeCertificate,
        [DescriptionResourceAttribute(Resource.String.instruction_place_exchange_certificate_1)]
        PlaceExchangeCertificate1,
        [DescriptionResourceAttribute(Resource.String.instruction_place_exchange_certificate_2)]
        PlaceExchangeCertificate2,
        [DescriptionResourceAttribute(Resource.String.instruction_place_exchange_certificate_3)]
        PlaceExchangeCertificate3,
        [DescriptionResourceAttribute(Resource.String.instruction_place_magical_buildings)]
        PlaceMagicalBuildings,
        [DescriptionResourceAttribute(Resource.String.instruction_place_new_building_grounds)]
        PlaceNewBuildingGrounds,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_major_construction_marker)]
        DealMajorConstructionMarker,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_servant_tiles)]
        ShuffleServantTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_orchards_boards)]
        ShuffleOrchardsBoards,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_orchards_fruits)]
        ShuffleOrchardsFruits,
        [DescriptionResourceAttribute(Resource.String.instruction_remove_craftsmen_5)]
        RemoveCraftsmen5,
        [DescriptionResourceAttribute(Resource.String.instruction_remove_craftsmen_6)]
        RemoveCraftsmen6,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_craftsmen)]
        DealCraftsmen,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_project_tiles)]
        ShuffleProjectTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_remove_project_tiles)]
        RemoveProjectTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_place_color_tiles)]
        PlaceColorTiles,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_palace_designers)]
        DealPalaceDesigners,
        [DescriptionResourceAttribute(Resource.String.instruction_place_palace_designers)]
        PlacePalaceDesigners,
        [DescriptionResourceAttribute(Resource.String.instruction_shuffle_animals)]
        ShuffleAnimals,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_handymen)]
        DealHandymen,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_personal_building_market)]
        DealPersonalBuildingMarket,
        [DescriptionResourceAttribute(Resource.String.instruction_deal_treasures)]
        DealTreasures,
        [DescriptionResourceAttribute(Resource.String.instruction_place_missions)]
        PlaceMissions,
    }
}